---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(stringr)
library(ggpubr)
library(ggbeeswarm)
library(ggprism)
```

```{r}
manualauto <- read.csv("../HighThroughputFecundityAssay/Data/1permanualvs2perauto.csv")
```

```{r}
manualauto <- manualauto %>% select(Condition, Repeat, Day, EggCounts, FileName)
```

#Graph showing different agarose concentrations with different model used (1% for hand counting and 2% using flymodel2 tool)
```{r}
ggplot(data = manualauto, aes(x = Condition, y = EggCounts, fill = Day)) + 
geom_boxplot() +
geom_point(position = position_dodge(width = 0.75)) +
theme_prism(base_size = 10) +
scale_fill_brewer(palette = "Blues") +
 xlab("Agarose Concentration + Model used") +
ylab("Number of Eggs Laid") 
#scale_x_discrete(limits=level_order, labels=c('1%'))
```


```{r}
manualauto <- manualauto %>% select(Condition, Repeat, Day, EggCounts, FileName)
```

```{r}
manualauto$well <- str_sub(manualauto$FileName, 6, 7)
manualauto$well <- str_remove(manualauto$well, "_")
manualauto$well <- as.numeric(manualauto$well)
```

```{r}
manualauto$row1 <- ifelse(manualauto$well < 9, 1, 0)
manualauto$row2 <- ifelse(manualauto$well > 8 & manualauto$well < 17, 2, 0)
manualauto$row3 <- ifelse(manualauto$well > 16 & manualauto$well < 25, 3, 0)
manualauto$row4 <- ifelse(manualauto$well > 24 & manualauto$well < 33, 4, 0)
manualauto$row5 <- ifelse(manualauto$well > 32 & manualauto$well < 41, 5, 0)
manualauto$row6 <- ifelse(manualauto$well > 40 & manualauto$well < 49, 6, 0)
```

```{r}
manualauto <- manualauto %>% rowwise() %>% mutate(row = sum(row1, row2, row3, row4, row5, row6))
```

```{r}
manualauto <- manualauto %>% select(Condition, Repeat, Day, EggCounts, FileName, row)
```

```{r}
manualauto.average <- manualauto %>% group_by(Condition, Repeat, Day, row) %>% summarise(Eggs = mean(EggCounts))
```
#Average number of eggs laid laid per model and agarose concentration
```{r}

ggplot(data = manualauto.average, aes(x = Condition, y = Eggs, fill = Day)) + 
geom_boxplot() +
geom_point(position = position_dodge(width = 0.75)) +
theme_prism(base_size = 10) +
scale_fill_brewer(palette = "Blues") +
 xlab("Agarose Concentration") +
ylab("Average Number of Eggs Laid") 
#scale_x_discrete(limits=level_order, labels=c('1%'))
```

