---
title: "1% agarose concentration - rate of fecundity"
output: html_notebook
---

```{r}
library(tidyverse)
library(stringr)
library(ggpubr)
library(ggbeeswarm)
library(ggprism)
```

```{r}
Oneperc_manual <- read.csv("../Data/1percent_manualcounts.csv")
```

```{r}
Oneperc_manual <- Oneperc_manual %>% select(Condition, Repeat, Day, EggCounts, FileName)
```

```{r}
level_order <- c('1percent_manual')

Oneperc_manual$Condition <- factor(Oneperc_manual$Condition, levels = level_order)
ggplot(data = Oneperc_manual, aes(x = Condition, y = EggCounts, fill = Day)) + 
geom_boxplot() +
theme_prism(base_size = 10) +
scale_fill_brewer(palette = "Blues") +
 xlab("Agarose Concentration") +
ylab("Number of Eggs Laid") +
scale_x_discrete(limits=level_order, labels=c('1%'))

ggsave("../Results/OnePercentAgarose.pdf", width = 110, height = 75, units = "mm")
```

```{r}
AltTx <- read.csv("../Data/AlternatingTimecourse.csv")
AltTx <- rename(AltTx, EggCounts = EggCount)
Comps <- rbind(Oneperc_manual[,1:4], AltTx[,2:5])
```

```{r}
compare_means(EggCounts ~ Condition, data = Comps, group.by = "Day", method = "t.test", p.adjust.method = "bonf")
```
```{r}
Comps %>% group_by(Day, Condition) %>% summarise(mean = mean(EggCounts), median = median(EggCounts))
```


