---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
```

```{r}
AllData <- read.csv("../Data/EggCountsD1D7_R1R7.2.csv")
```

```{r}
AllData <- AllData %>% select(Condition, Repeat, Day, EggCount, FileName ) 
```

```{r}
AllData$well <- str_sub(AllData$FileName, 6, 7)
AllData$well <- str_remove(AllData$well, "_")
AllData$well <- as.numeric(AllData$well)
```

```{r}
AllData$row1 <- ifelse(AllData$well < 9, 1, 0)
AllData$row2 <- ifelse(AllData$well > 8 & AllData$well < 17, 2, 0)
AllData$row3 <- ifelse(AllData$well > 16 & AllData$well < 25, 3, 0)
AllData$row4 <- ifelse(AllData$well > 24 & AllData$well < 33, 4, 0)
AllData$row5 <- ifelse(AllData$well > 32 & AllData$well < 41, 5, 0)
AllData$row6 <- ifelse(AllData$well > 40 & AllData$well < 49, 6, 0)
```

```{r}
AllData <- AllData %>% rowwise() %>% mutate(row = sum(row1, row2, row3, row4, row5, row6))
```

```{r}
AllData <- AllData %>% select(Condition, Repeat, Day, EggCount, FileName, row ) 
```

```{r}
AllData.average <- AllData %>% group_by(Condition, Repeat, Day, row) %>% summarise(Eggs = mean(EggCount))
AllData.average <- AllData.average %>% filter(Condition != "WT")
```

```{r}
anova.1 <- AllData.average %>% filter(Day == "D1") %>% aov(data = ., Eggs ~ Condition)
summary(anova.1)
TukeyHSD(anova.1)
```

```{r}
anova.3 <- AllData.average %>% filter(Day == "D3") %>% aov(data = ., Eggs ~ Condition)
summary(anova.3)
TukeyHSD(anova.3)
```

```{r}
anova.7 <- AllData.average %>% filter(Day == "D7") %>% aov(data = ., Eggs ~ Condition)
summary(anova.7)
TukeyHSD(anova.7)
```
