---
title: "R Notebook"
output: pdf
---
```{r}
library(tidyverse)
library(stringr)
library(ggpubr)
library(ggbeeswarm)
library(ggprism)
```


```{r}
DR <- read.csv("../Data/DMSOvsRapamycin.csv")
```

```{r}
DR <- DR %>% select(Condition, Repeat, Day, EggCount, FileName )
```

```{r}
DR$well <- str_sub(DR$FileName, 6, 7)
DR$well <- str_remove(DR$well, "_")
DR$well <- as.numeric(DR$well) 
```

```{r}
DR$row1 <- ifelse(DR$well < 9, 1, 0)
DR$row2 <- ifelse(DR$well > 8 & DR$well < 17, 2, 0)
DR$row3 <- ifelse(DR$well > 16 & DR$well < 25, 3, 0)
DR$row4 <- ifelse(DR$well > 24 & DR$well < 33, 4, 0)
DR$row5 <- ifelse(DR$well > 32 & DR$well < 41, 5, 0)
DR$row6 <- ifelse(DR$well > 40 & DR$well < 49, 6, 0) 
```

```{r}
DR <- DR %>% rowwise() %>% mutate(row = sum(row1, row2, row3, row4, row5, row6)) 
```

```{r}
DR <- DR %>% select(Condition, Repeat, Day, EggCount, FileName, row )  
```

```{r}
DR.average <- DR %>% group_by(Condition, Repeat, Day, row) %>% summarise(Eggs = mean(EggCount)) 
```


```{r}
level_order <- c('DMSO', 'Rap_0.1', 'Rap_10', 'Rap_25')

DR.average$Condition <- factor(DR.average$Condition, levels = level_order)
ggplot(data = DR.average, aes(x = Condition, y = Eggs, fill = Day)) + 
  geom_boxplot() +
  geom_point(position = position_dodge(width = 0.75)) +
  theme_prism(base_size = 10) +
  scale_fill_brewer(palette = "Blues") +
  xlab("Chemicals") +
  ylab("Average Amount of Eggs Laid") +
  scale_x_discrete(labels = c('0.1% DMS0', 'rapamycin (0.1 uM)', 'rapamycin (10 uM)', 'rapamycin (25 uM)'))

    
ggsave("../Results/DMSOvsRapamycin.pdf")
```
