---
title: "R Notebook"
output: PDF
---

```{r}
library(tidyverse)
library(ggprism)
```

```{r}
img_count <- read.csv("../Data/ImagePipeline.csv")
```

```{r}
#versatile flow model
ggplot(data = img_count, aes(x = Manual, y = Versatile_fluo)) +
  geom_point() +
  geom_smooth(method = 'lm', se = FALSE) +
  theme_prism(base_size = 10) +
  xlab("Manual counts") +
  ylab("Model counts") +
  scale_x_continuous(limits = c(0,100), breaks = c(seq(0,100, by=20))) +
  scale_y_continuous(limits = c(0,100), breaks = c(seq(0,100, by=20))) + 
  theme(
    axis.text = element_text(size = 24),
    axis.title = element_text(size = 24)
  )

ggsave("../Results/versatile_fluo.pdf")
```
```{r}
summary(lm(Versatile_fluo ~ Manual, data = img_count))
```

```{r}
#flyModel2 model
ggplot(data = img_count, aes(x = Manual, y = flyModel2)) +
  geom_point() +
  geom_smooth(method = 'lm', se = FALSE) +
  theme_prism(base_size = 10) +
  xlab("Manual counts") +
  ylab("Model counts") +
  scale_x_continuous(limits = c(0,100), breaks = c(seq(0,100, by=20))) +
  scale_y_continuous(limits = c(0,100), breaks = c(seq(0,100, by=20)))

ggsave("../Results/flyModel2.pdf")
```

```{r}
summary(lm(flyModel2 ~ Manual, data = img_count))
```

```{r}
#Quantifly
ggplot(data = img_count, aes(x = Manual, y = Quantifly)) +
  geom_point() +
  geom_smooth(method = 'lm', se = FALSE) +
  theme_prism(base_size = 10) +
  xlab("Manual counts") +
  ylab("Model counts") +
  scale_x_continuous(limits = c(0,100), breaks = c(seq(0,100, by=20))) +
  scale_y_continuous(limits = c(0,120), breaks = c(seq(0,120, by=20)))

ggsave("../Results/Quantifly.pdf")
```

```{r}
summary(lm(Quantifly ~ Manual, data = img_count))
```

```{r}
#calculate the error of each model
img_count_error <- data.frame(
  Versatile_fluo = img_count$Versatile_fluo - img_count$Manual,
  flyModel2 = img_count$flyModel2 - img_count$Manual,
  Quantifly = img_count$Quantifly - img_count$Manual
)

img_count_error <- img_count_error %>% rownames_to_column()
img_count_error <- img_count_error %>% pivot_longer(!rowname, names_to = "Model", values_to = "Values")
```

```{r}
img_count_error$Model <- factor(img_count_error$Model, levels = c("Versatile_fluo", "flyModel2", "Quantifly"))
ggplot(data = img_count_error, aes(x = Model, y = Values, fill = Model)) +
  geom_violin() +
  geom_jitter(width = 0.1, size = 0.2) +
  theme_prism(base_size = 10) +
  scale_fill_brewer(palette = "Blues") +
  theme(legend.position = "None") +
  xlab("") +
  ylab("Difference betwen model and ground truth")

ggsave("../Results/ModelErrors.pdf")
```

