---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(stringr)
library(ggpubr)
library(ggbeeswarm)
library(ggprism)
```

```{r}
DB <- read.csv("../Data/DMSOvsBendiocarb.csv")
```

```{r}
DB <- DB %>% select(Condition, Repeat, Day, EggCount, FileName ) 
```

```{r}
DB$well <- str_sub(DB$FileName, 6, 7)
DB$well <- str_remove(DB$well, "_")
DB$well <- as.numeric(DB$well)
```

```{r}
DB$row1 <- ifelse(DB$well < 9, 1, 0)
DB$row2 <- ifelse(DB$well > 8 & DB$well < 17, 2, 0)
DB$row3 <- ifelse(DB$well > 16 & DB$well < 25, 3, 0)
DB$row4 <- ifelse(DB$well > 24 & DB$well < 33, 4, 0)
DB$row5 <- ifelse(DB$well > 32 & DB$well < 41, 5, 0)
DB$row6 <- ifelse(DB$well > 40 & DB$well < 49, 6, 0)
```

```{r}
DB <- DB %>% rowwise() %>% mutate(row = sum(row1, row2, row3, row4, row5, row6))
```

```{r}
DB <- DB %>% select(Condition, Repeat, Day, EggCount, FileName, row ) 
```

```{r}
DB.average <- DB %>% group_by(Condition, Repeat, Day, row) %>% summarise(Eggs = mean(EggCount))
```

```{r}
level_order <- c('DMSO', 'Chem3_0.1', 'Chem3_10', 'Chem3_25')

DB.average$Condition <- factor(DB.average$Condition, levels = level_order)
ggplot(data = DB.average, aes(x = Condition, y = Eggs, fill = Day)) + 
geom_boxplot() +
geom_point(position = position_dodge(width = 0.75)) +
theme_prism(base_size = 10) +
scale_fill_brewer(palette = "Blues") +
  xlab("Chemicals") +
  ylab("Average Amount of Eggs Laid") +
 scale_x_discrete(labels = c('0.1% DMS0', 'bendiocarb (0.1 uM)', 'bendiocarb (10 uM)', 'bendiocarb (25 uM)')) +
   theme (
    axis.text = element_text(size = 22),
    axis.title = element_text(size = 22),
  )

ggsave("../Results/DMSOvs.Bendiocarb.pdf")
```



