---
title: "Feeding flies different food types and analyzing their egg lay number"
output: html_notebook
---

```{r}
library(tidyverse)
library(ggprism)
library(ggpubr)
```

```{r}
#Load data from four replicates

FoodTypes1 <- read.csv("../Data/FoodTypes_20221211_1214.csv")
FoodTypes2 <- read.csv("../Data/FoodTypes_20221220_1222.csv")
FoodTypes3 <- read.csv("../Data/FoodTypes_20230125_0127.csv")
FoodTypes4 <- read.csv("../Data/FoodTypes_20230208_0210.csv")
```

```{r}
FoodTypes1$Repeat = 1
FoodTypes2$Repeat = 2
FoodTypes3$Repeat = 3
FoodTypes4$Repeat = 4
FoodTypes = rbind(FoodTypes1, FoodTypes2, FoodTypes3, FoodTypes4)
```

```{r}
level_order <- c('Molasses', 'BDSC', 'Grape Juice')

FoodTypes$Condition <- str_trim(FoodTypes$Condition)
FoodTypes$Condition <- factor(FoodTypes$Condition, levels = level_order)

ggplot(data = FoodTypes, aes(x = Condition, y = Value, fill = Day)) + 
  geom_boxplot(outlier.size = 0.3) +
  theme_prism(base_size = 10) +
  scale_fill_brewer(palette = "Blues") +
  xlab("Media type") +
  ylab("Number of eggs per well") +
  theme (
    axis.text = element_text(size = 10, face = "bold"),
    axis.title = element_text(size = 10, face = "bold"),
    legend.text = element_text(size = 8, face = "bold")
  ) +
  scale_y_continuous(limits = c(0,150))
  

ggsave("../Results/Figure1.pdf", width = 110, height = 75, units = "mm")
```

```{r}
compare_means(Value ~ Day, data = FoodTypes[FoodTypes$Condition == "Grape Juice",], method = "t.test", p.adjust.method = "bonf")
```

```{r}
compare_means(Value ~ Day, data = FoodTypes[FoodTypes$Condition == "Molasses",], method = "t.test", p.adjust.method = "bonf")
```

```{r}
compare_means(Value ~ Day, data = FoodTypes[FoodTypes$Condition == "BDSC",], method = "t.test", p.adjust.method = "bonf")
```

```{r}
sd(FoodTypes[FoodTypes$Condition == "Grape Juice" & FoodTypes$Day == "D1", "Value"])
```

